apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-demo
  annotations:
    argocd/app-name: nginx-demo
    argocd/app-namespace: default
spec:
  type: service
  lifecycle: experimental
  owner: user:default/minkzaw
  consumesApis: [api:default/example-grpc-api]
